nodeLinker: pnp

# Yarn PnP 환경에서 일부 레거시 패키지들이 정상 작동하도록 느슨하게 만드는 설정
# Webpack, Babel, ESLint 같은 도구 + PnP 환경에서 "의존성 못 찾음" 오류를 낼 때 이 옵션 필요
pnpMode: loose
# packageExtensions:
#   react@*:
#     peerDependencies:
#       react-dom: "*"
